// Mocks generated by Mockito 5.4.4 from annotations
// in video_player_linux/test/linux_video_player_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;

import 'test_api.g.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TestHostVideoPlayerApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestHostVideoPlayerApi extends _i1.Mock
    implements _i2.TestHostVideoPlayerApi {
  MockTestHostVideoPlayerApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int create(
    String? asset,
    String? uri,
    Map<String?, String?>? httpHeaders,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            asset,
            uri,
            httpHeaders,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  void dispose(int? textureId) => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [textureId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLooping(
    int? textureId,
    bool? isLooping,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setLooping,
          [
            textureId,
            isLooping,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setVolume(
    int? textureId,
    double? volume,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [
            textureId,
            volume,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPlaybackSpeed(
    int? textureId,
    double? speed,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setPlaybackSpeed,
          [
            textureId,
            speed,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void play(int? textureId) => super.noSuchMethod(
        Invocation.method(
          #play,
          [textureId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getPosition(int? textureId) => (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [textureId],
        ),
        returnValue: 0,
      ) as int);

  @override
  void seekTo(
    int? textureId,
    int? position,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [
            textureId,
            position,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pause(int? textureId) => super.noSuchMethod(
        Invocation.method(
          #pause,
          [textureId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getAudioTrackCount(int? textureId) => (super.noSuchMethod(
        Invocation.method(
          #getAudioTrackCount,
          [textureId],
        ),
        returnValue: 0,
      ) as int);

  @override
  void setAudioTrack(
    int? textureId,
    int? trackIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAudioTrack,
          [
            textureId,
            trackIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOutputChannels(
    int? textureId,
    int? channels,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setOutputChannels,
          [
            textureId,
            channels,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMute(
    int? textureId,
    bool? mute,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setMute,
          [
            textureId,
            mute,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isAudioOnly(int? textureId) => (super.noSuchMethod(
        Invocation.method(
          #isAudioOnly,
          [textureId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setScaleMethod(
    int? textureId,
    int? method,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setScaleMethod,
          [
            textureId,
            method,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAVOffset(
    int? textureId,
    int? offsetMs,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAVOffset,
          [
            textureId,
            offsetMs,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSubtitlesEnabled(
    int? textureId,
    bool? enabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSubtitlesEnabled,
          [
            textureId,
            enabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getSubtitleTrackCount(int? textureId) => (super.noSuchMethod(
        Invocation.method(
          #getSubtitleTrackCount,
          [textureId],
        ),
        returnValue: 0,
      ) as int);

  @override
  void setSubtitleTrack(
    int? textureId,
    int? trackIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSubtitleTrack,
          [
            textureId,
            trackIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSubtitleUri(
    int? textureId,
    String? uri,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSubtitleUri,
          [
            textureId,
            uri,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSubtitleFont(
    int? textureId,
    String? fontDesc,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSubtitleFont,
          [
            textureId,
            fontDesc,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setChannelMixPreset(
    int? textureId,
    String? preset,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setChannelMixPreset,
          [
            textureId,
            preset,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEqualizer(
    int? textureId,
    List<double?>? bands,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setEqualizer,
          [
            textureId,
            bands,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setVideoBalance(
    int? textureId,
    double? brightness,
    double? contrast,
    double? saturation,
    double? hue,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setVideoBalance,
          [
            textureId,
            brightness,
            contrast,
            saturation,
            hue,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAudioPassthrough(
    int? textureId,
    bool? enabled,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAudioPassthrough,
          [
            textureId,
            enabled,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setChannelMixMatrix(
    int? textureId,
    int? inChannels,
    int? outChannels,
    List<double?>? matrix,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setChannelMixMatrix,
          [
            textureId,
            inChannels,
            outChannels,
            matrix,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
