// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace video_player_linux {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by LinuxVideoPlayerApi.
const flutter::StandardMessageCodec& LinuxVideoPlayerApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `LinuxVideoPlayerApi` to handle messages through the `binary_messenger`.
void LinuxVideoPlayerApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  LinuxVideoPlayerApi* api) {
  LinuxVideoPlayerApi::SetUp(binary_messenger, api, "");
}

void LinuxVideoPlayerApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  LinuxVideoPlayerApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.initialize" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Initialize();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.create" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_asset_arg = args.at(0);
          if (encodable_asset_arg.IsNull()) {
            reply(WrapError("asset_arg unexpectedly null."));
            return;
          }
          const auto& asset_arg = std::get<std::string>(encodable_asset_arg);
          const auto& encodable_uri_arg = args.at(1);
          if (encodable_uri_arg.IsNull()) {
            reply(WrapError("uri_arg unexpectedly null."));
            return;
          }
          const auto& uri_arg = std::get<std::string>(encodable_uri_arg);
          const auto& encodable_http_headers_arg = args.at(2);
          if (encodable_http_headers_arg.IsNull()) {
            reply(WrapError("http_headers_arg unexpectedly null."));
            return;
          }
          const auto& http_headers_arg = std::get<EncodableMap>(encodable_http_headers_arg);
          ErrorOr<int64_t> output = api->Create(asset_arg, uri_arg, http_headers_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.dispose" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          std::optional<FlutterError> output = api->Dispose(texture_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setLooping" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_is_looping_arg = args.at(1);
          if (encodable_is_looping_arg.IsNull()) {
            reply(WrapError("is_looping_arg unexpectedly null."));
            return;
          }
          const auto& is_looping_arg = std::get<bool>(encodable_is_looping_arg);
          std::optional<FlutterError> output = api->SetLooping(texture_id_arg, is_looping_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setVolume" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_volume_arg = args.at(1);
          if (encodable_volume_arg.IsNull()) {
            reply(WrapError("volume_arg unexpectedly null."));
            return;
          }
          const auto& volume_arg = std::get<double>(encodable_volume_arg);
          std::optional<FlutterError> output = api->SetVolume(texture_id_arg, volume_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setPlaybackSpeed" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_speed_arg = args.at(1);
          if (encodable_speed_arg.IsNull()) {
            reply(WrapError("speed_arg unexpectedly null."));
            return;
          }
          const auto& speed_arg = std::get<double>(encodable_speed_arg);
          std::optional<FlutterError> output = api->SetPlaybackSpeed(texture_id_arg, speed_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.play" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          std::optional<FlutterError> output = api->Play(texture_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.getPosition" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          ErrorOr<int64_t> output = api->GetPosition(texture_id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.seekTo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_position_arg = args.at(1);
          if (encodable_position_arg.IsNull()) {
            reply(WrapError("position_arg unexpectedly null."));
            return;
          }
          const int64_t position_arg = encodable_position_arg.LongValue();
          std::optional<FlutterError> output = api->SeekTo(texture_id_arg, position_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.pause" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          std::optional<FlutterError> output = api->Pause(texture_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.getAudioTrackCount" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          ErrorOr<int64_t> output = api->GetAudioTrackCount(texture_id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setAudioTrack" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_track_index_arg = args.at(1);
          if (encodable_track_index_arg.IsNull()) {
            reply(WrapError("track_index_arg unexpectedly null."));
            return;
          }
          const int64_t track_index_arg = encodable_track_index_arg.LongValue();
          std::optional<FlutterError> output = api->SetAudioTrack(texture_id_arg, track_index_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setOutputChannels" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_channels_arg = args.at(1);
          if (encodable_channels_arg.IsNull()) {
            reply(WrapError("channels_arg unexpectedly null."));
            return;
          }
          const int64_t channels_arg = encodable_channels_arg.LongValue();
          std::optional<FlutterError> output = api->SetOutputChannels(texture_id_arg, channels_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setMute" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_mute_arg = args.at(1);
          if (encodable_mute_arg.IsNull()) {
            reply(WrapError("mute_arg unexpectedly null."));
            return;
          }
          const auto& mute_arg = std::get<bool>(encodable_mute_arg);
          std::optional<FlutterError> output = api->SetMute(texture_id_arg, mute_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.isAudioOnly" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          ErrorOr<bool> output = api->IsAudioOnly(texture_id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setScaleMethod" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_method_arg = args.at(1);
          if (encodable_method_arg.IsNull()) {
            reply(WrapError("method_arg unexpectedly null."));
            return;
          }
          const int64_t method_arg = encodable_method_arg.LongValue();
          std::optional<FlutterError> output = api->SetScaleMethod(texture_id_arg, method_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setAVOffset" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_offset_ms_arg = args.at(1);
          if (encodable_offset_ms_arg.IsNull()) {
            reply(WrapError("offset_ms_arg unexpectedly null."));
            return;
          }
          const int64_t offset_ms_arg = encodable_offset_ms_arg.LongValue();
          std::optional<FlutterError> output = api->SetAVOffset(texture_id_arg, offset_ms_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setSubtitlesEnabled" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_enabled_arg = args.at(1);
          if (encodable_enabled_arg.IsNull()) {
            reply(WrapError("enabled_arg unexpectedly null."));
            return;
          }
          const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
          std::optional<FlutterError> output = api->SetSubtitlesEnabled(texture_id_arg, enabled_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.getSubtitleTrackCount" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          ErrorOr<int64_t> output = api->GetSubtitleTrackCount(texture_id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setSubtitleTrack" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_track_index_arg = args.at(1);
          if (encodable_track_index_arg.IsNull()) {
            reply(WrapError("track_index_arg unexpectedly null."));
            return;
          }
          const int64_t track_index_arg = encodable_track_index_arg.LongValue();
          std::optional<FlutterError> output = api->SetSubtitleTrack(texture_id_arg, track_index_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setSubtitleUri" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_uri_arg = args.at(1);
          if (encodable_uri_arg.IsNull()) {
            reply(WrapError("uri_arg unexpectedly null."));
            return;
          }
          const auto& uri_arg = std::get<std::string>(encodable_uri_arg);
          std::optional<FlutterError> output = api->SetSubtitleUri(texture_id_arg, uri_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setSubtitleFont" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_font_desc_arg = args.at(1);
          if (encodable_font_desc_arg.IsNull()) {
            reply(WrapError("font_desc_arg unexpectedly null."));
            return;
          }
          const auto& font_desc_arg = std::get<std::string>(encodable_font_desc_arg);
          std::optional<FlutterError> output = api->SetSubtitleFont(texture_id_arg, font_desc_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setChannelMixPreset" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_preset_arg = args.at(1);
          if (encodable_preset_arg.IsNull()) {
            reply(WrapError("preset_arg unexpectedly null."));
            return;
          }
          const auto& preset_arg = std::get<std::string>(encodable_preset_arg);
          std::optional<FlutterError> output = api->SetChannelMixPreset(texture_id_arg, preset_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setEqualizer" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_bands_arg = args.at(1);
          if (encodable_bands_arg.IsNull()) {
            reply(WrapError("bands_arg unexpectedly null."));
            return;
          }
          const auto& bands_arg = std::get<EncodableList>(encodable_bands_arg);
          std::optional<FlutterError> output = api->SetEqualizer(texture_id_arg, bands_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setVideoBalance" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_brightness_arg = args.at(1);
          if (encodable_brightness_arg.IsNull()) {
            reply(WrapError("brightness_arg unexpectedly null."));
            return;
          }
          const auto& brightness_arg = std::get<double>(encodable_brightness_arg);
          const auto& encodable_contrast_arg = args.at(2);
          if (encodable_contrast_arg.IsNull()) {
            reply(WrapError("contrast_arg unexpectedly null."));
            return;
          }
          const auto& contrast_arg = std::get<double>(encodable_contrast_arg);
          const auto& encodable_saturation_arg = args.at(3);
          if (encodable_saturation_arg.IsNull()) {
            reply(WrapError("saturation_arg unexpectedly null."));
            return;
          }
          const auto& saturation_arg = std::get<double>(encodable_saturation_arg);
          const auto& encodable_hue_arg = args.at(4);
          if (encodable_hue_arg.IsNull()) {
            reply(WrapError("hue_arg unexpectedly null."));
            return;
          }
          const auto& hue_arg = std::get<double>(encodable_hue_arg);
          std::optional<FlutterError> output = api->SetVideoBalance(texture_id_arg, brightness_arg, contrast_arg, saturation_arg, hue_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setAudioPassthrough" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_enabled_arg = args.at(1);
          if (encodable_enabled_arg.IsNull()) {
            reply(WrapError("enabled_arg unexpectedly null."));
            return;
          }
          const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
          std::optional<FlutterError> output = api->SetAudioPassthrough(texture_id_arg, enabled_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.video_player_linux.LinuxVideoPlayerApi.setChannelMixMatrix" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_texture_id_arg = args.at(0);
          if (encodable_texture_id_arg.IsNull()) {
            reply(WrapError("texture_id_arg unexpectedly null."));
            return;
          }
          const int64_t texture_id_arg = encodable_texture_id_arg.LongValue();
          const auto& encodable_in_channels_arg = args.at(1);
          if (encodable_in_channels_arg.IsNull()) {
            reply(WrapError("in_channels_arg unexpectedly null."));
            return;
          }
          const int64_t in_channels_arg = encodable_in_channels_arg.LongValue();
          const auto& encodable_out_channels_arg = args.at(2);
          if (encodable_out_channels_arg.IsNull()) {
            reply(WrapError("out_channels_arg unexpectedly null."));
            return;
          }
          const int64_t out_channels_arg = encodable_out_channels_arg.LongValue();
          const auto& encodable_matrix_arg = args.at(3);
          if (encodable_matrix_arg.IsNull()) {
            reply(WrapError("matrix_arg unexpectedly null."));
            return;
          }
          const auto& matrix_arg = std::get<EncodableList>(encodable_matrix_arg);
          std::optional<FlutterError> output = api->SetChannelMixMatrix(texture_id_arg, in_channels_arg, out_channels_arg, matrix_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue LinuxVideoPlayerApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue LinuxVideoPlayerApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace video_player_linux
