name: my_fox_example
description: Demonstrates how to use the playx 3d Scene plugin to show 3d model.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: 1.1.0
  provider: ^6.1.5

  filament_scene:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  pigeon: ^22.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/envs/
    - assets/envs/venetian_crossroads_2k/
    - assets/models/
    - assets/models/textures/
    - assets/materials/
    - assets/materials/texture/
  fonts:
    - family: Galmuri7
      fonts:
        - asset: assets/fonts/Galmuri/Galmuri7.ttf
          weight: 400
    - family: GalmuriMono7
      fonts:
        - asset: assets/fonts/Galmuri/GalmuriMono7.ttf
          weight: 400
    - family: Galmuri9
      fonts:
        - asset: assets/fonts/Galmuri/Galmuri9.ttf
          weight: 400
    - family: GalmuriMono9
      fonts:
        - asset: assets/fonts/Galmuri/GalmuriMono9.ttf
          weight: 400
    - family: Galmuri11
      fonts:
        - asset: assets/fonts/Galmuri/Galmuri11.ttf
          weight: 400
        - asset: assets/fonts/Galmuri/Galmuri11-Bold.ttf
          weight: 700
    - family: GalmuriMono11
      fonts:
        - asset: assets/fonts/Galmuri/GalmuriMono11.ttf
          weight: 400
    - family: Galmuri14
      fonts:
        - asset: assets/fonts/Galmuri/Galmuri14.ttf
          weight: 400
    
