// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

G_DECLARE_FINAL_TYPE(video_player_linuxMessageCodec, video_player_linux_message_codec, VIDEO_PLAYER_LINUX, MESSAGE_CODEC, FlStandardMessageCodec)

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApi, video_player_linux_linux_video_player_api, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API, GObject)

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiInitializeResponse, video_player_linux_linux_video_player_api_initialize_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_INITIALIZE_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_initialize_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.initialize.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiInitializeResponse
 */
video_player_linuxLinuxVideoPlayerApiInitializeResponse* video_player_linux_linux_video_player_api_initialize_response_new();

/**
 * video_player_linux_linux_video_player_api_initialize_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.initialize.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiInitializeResponse
 */
video_player_linuxLinuxVideoPlayerApiInitializeResponse* video_player_linux_linux_video_player_api_initialize_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiCreateResponse, video_player_linux_linux_video_player_api_create_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_CREATE_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_create_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.create.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiCreateResponse
 */
video_player_linuxLinuxVideoPlayerApiCreateResponse* video_player_linux_linux_video_player_api_create_response_new(int64_t return_value);

/**
 * video_player_linux_linux_video_player_api_create_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.create.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiCreateResponse
 */
video_player_linuxLinuxVideoPlayerApiCreateResponse* video_player_linux_linux_video_player_api_create_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiDisposeResponse, video_player_linux_linux_video_player_api_dispose_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_DISPOSE_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_dispose_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.dispose.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiDisposeResponse
 */
video_player_linuxLinuxVideoPlayerApiDisposeResponse* video_player_linux_linux_video_player_api_dispose_response_new();

/**
 * video_player_linux_linux_video_player_api_dispose_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.dispose.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiDisposeResponse
 */
video_player_linuxLinuxVideoPlayerApiDisposeResponse* video_player_linux_linux_video_player_api_dispose_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetLoopingResponse, video_player_linux_linux_video_player_api_set_looping_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_LOOPING_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_looping_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setLooping.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetLoopingResponse
 */
video_player_linuxLinuxVideoPlayerApiSetLoopingResponse* video_player_linux_linux_video_player_api_set_looping_response_new();

/**
 * video_player_linux_linux_video_player_api_set_looping_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setLooping.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetLoopingResponse
 */
video_player_linuxLinuxVideoPlayerApiSetLoopingResponse* video_player_linux_linux_video_player_api_set_looping_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetVolumeResponse, video_player_linux_linux_video_player_api_set_volume_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_VOLUME_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_volume_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setVolume.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetVolumeResponse
 */
video_player_linuxLinuxVideoPlayerApiSetVolumeResponse* video_player_linux_linux_video_player_api_set_volume_response_new();

/**
 * video_player_linux_linux_video_player_api_set_volume_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setVolume.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetVolumeResponse
 */
video_player_linuxLinuxVideoPlayerApiSetVolumeResponse* video_player_linux_linux_video_player_api_set_volume_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetPlaybackSpeedResponse, video_player_linux_linux_video_player_api_set_playback_speed_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_PLAYBACK_SPEED_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_playback_speed_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setPlaybackSpeed.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetPlaybackSpeedResponse
 */
video_player_linuxLinuxVideoPlayerApiSetPlaybackSpeedResponse* video_player_linux_linux_video_player_api_set_playback_speed_response_new();

/**
 * video_player_linux_linux_video_player_api_set_playback_speed_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setPlaybackSpeed.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetPlaybackSpeedResponse
 */
video_player_linuxLinuxVideoPlayerApiSetPlaybackSpeedResponse* video_player_linux_linux_video_player_api_set_playback_speed_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiPlayResponse, video_player_linux_linux_video_player_api_play_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_PLAY_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_play_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.play.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiPlayResponse
 */
video_player_linuxLinuxVideoPlayerApiPlayResponse* video_player_linux_linux_video_player_api_play_response_new();

/**
 * video_player_linux_linux_video_player_api_play_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.play.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiPlayResponse
 */
video_player_linuxLinuxVideoPlayerApiPlayResponse* video_player_linux_linux_video_player_api_play_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiGetPositionResponse, video_player_linux_linux_video_player_api_get_position_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_GET_POSITION_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_get_position_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.getPosition.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiGetPositionResponse
 */
video_player_linuxLinuxVideoPlayerApiGetPositionResponse* video_player_linux_linux_video_player_api_get_position_response_new(int64_t return_value);

/**
 * video_player_linux_linux_video_player_api_get_position_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.getPosition.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiGetPositionResponse
 */
video_player_linuxLinuxVideoPlayerApiGetPositionResponse* video_player_linux_linux_video_player_api_get_position_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSeekToResponse, video_player_linux_linux_video_player_api_seek_to_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SEEK_TO_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_seek_to_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.seekTo.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSeekToResponse
 */
video_player_linuxLinuxVideoPlayerApiSeekToResponse* video_player_linux_linux_video_player_api_seek_to_response_new();

/**
 * video_player_linux_linux_video_player_api_seek_to_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.seekTo.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSeekToResponse
 */
video_player_linuxLinuxVideoPlayerApiSeekToResponse* video_player_linux_linux_video_player_api_seek_to_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiPauseResponse, video_player_linux_linux_video_player_api_pause_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_PAUSE_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_pause_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.pause.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiPauseResponse
 */
video_player_linuxLinuxVideoPlayerApiPauseResponse* video_player_linux_linux_video_player_api_pause_response_new();

/**
 * video_player_linux_linux_video_player_api_pause_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.pause.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiPauseResponse
 */
video_player_linuxLinuxVideoPlayerApiPauseResponse* video_player_linux_linux_video_player_api_pause_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiGetAudioTrackCountResponse, video_player_linux_linux_video_player_api_get_audio_track_count_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_GET_AUDIO_TRACK_COUNT_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_get_audio_track_count_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.getAudioTrackCount.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiGetAudioTrackCountResponse
 */
video_player_linuxLinuxVideoPlayerApiGetAudioTrackCountResponse* video_player_linux_linux_video_player_api_get_audio_track_count_response_new(int64_t return_value);

/**
 * video_player_linux_linux_video_player_api_get_audio_track_count_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.getAudioTrackCount.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiGetAudioTrackCountResponse
 */
video_player_linuxLinuxVideoPlayerApiGetAudioTrackCountResponse* video_player_linux_linux_video_player_api_get_audio_track_count_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetAudioTrackResponse, video_player_linux_linux_video_player_api_set_audio_track_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_AUDIO_TRACK_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_audio_track_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setAudioTrack.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetAudioTrackResponse
 */
video_player_linuxLinuxVideoPlayerApiSetAudioTrackResponse* video_player_linux_linux_video_player_api_set_audio_track_response_new();

/**
 * video_player_linux_linux_video_player_api_set_audio_track_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setAudioTrack.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetAudioTrackResponse
 */
video_player_linuxLinuxVideoPlayerApiSetAudioTrackResponse* video_player_linux_linux_video_player_api_set_audio_track_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetOutputChannelsResponse, video_player_linux_linux_video_player_api_set_output_channels_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_OUTPUT_CHANNELS_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_output_channels_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setOutputChannels.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetOutputChannelsResponse
 */
video_player_linuxLinuxVideoPlayerApiSetOutputChannelsResponse* video_player_linux_linux_video_player_api_set_output_channels_response_new();

/**
 * video_player_linux_linux_video_player_api_set_output_channels_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setOutputChannels.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetOutputChannelsResponse
 */
video_player_linuxLinuxVideoPlayerApiSetOutputChannelsResponse* video_player_linux_linux_video_player_api_set_output_channels_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetMuteResponse, video_player_linux_linux_video_player_api_set_mute_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_MUTE_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_mute_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setMute.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetMuteResponse
 */
video_player_linuxLinuxVideoPlayerApiSetMuteResponse* video_player_linux_linux_video_player_api_set_mute_response_new();

/**
 * video_player_linux_linux_video_player_api_set_mute_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setMute.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetMuteResponse
 */
video_player_linuxLinuxVideoPlayerApiSetMuteResponse* video_player_linux_linux_video_player_api_set_mute_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiIsAudioOnlyResponse, video_player_linux_linux_video_player_api_is_audio_only_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_IS_AUDIO_ONLY_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_is_audio_only_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.isAudioOnly.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiIsAudioOnlyResponse
 */
video_player_linuxLinuxVideoPlayerApiIsAudioOnlyResponse* video_player_linux_linux_video_player_api_is_audio_only_response_new(gboolean return_value);

/**
 * video_player_linux_linux_video_player_api_is_audio_only_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.isAudioOnly.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiIsAudioOnlyResponse
 */
video_player_linuxLinuxVideoPlayerApiIsAudioOnlyResponse* video_player_linux_linux_video_player_api_is_audio_only_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetScaleMethodResponse, video_player_linux_linux_video_player_api_set_scale_method_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_SCALE_METHOD_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_scale_method_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setScaleMethod.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetScaleMethodResponse
 */
video_player_linuxLinuxVideoPlayerApiSetScaleMethodResponse* video_player_linux_linux_video_player_api_set_scale_method_response_new();

/**
 * video_player_linux_linux_video_player_api_set_scale_method_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setScaleMethod.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetScaleMethodResponse
 */
video_player_linuxLinuxVideoPlayerApiSetScaleMethodResponse* video_player_linux_linux_video_player_api_set_scale_method_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetAVOffsetResponse, video_player_linux_linux_video_player_api_set_a_v_offset_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_A_V_OFFSET_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_a_v_offset_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setAVOffset.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetAVOffsetResponse
 */
video_player_linuxLinuxVideoPlayerApiSetAVOffsetResponse* video_player_linux_linux_video_player_api_set_a_v_offset_response_new();

/**
 * video_player_linux_linux_video_player_api_set_a_v_offset_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setAVOffset.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetAVOffsetResponse
 */
video_player_linuxLinuxVideoPlayerApiSetAVOffsetResponse* video_player_linux_linux_video_player_api_set_a_v_offset_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetSubtitlesEnabledResponse, video_player_linux_linux_video_player_api_set_subtitles_enabled_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_SUBTITLES_ENABLED_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_subtitles_enabled_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setSubtitlesEnabled.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetSubtitlesEnabledResponse
 */
video_player_linuxLinuxVideoPlayerApiSetSubtitlesEnabledResponse* video_player_linux_linux_video_player_api_set_subtitles_enabled_response_new();

/**
 * video_player_linux_linux_video_player_api_set_subtitles_enabled_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setSubtitlesEnabled.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetSubtitlesEnabledResponse
 */
video_player_linuxLinuxVideoPlayerApiSetSubtitlesEnabledResponse* video_player_linux_linux_video_player_api_set_subtitles_enabled_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiGetSubtitleTrackCountResponse, video_player_linux_linux_video_player_api_get_subtitle_track_count_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_GET_SUBTITLE_TRACK_COUNT_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_get_subtitle_track_count_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.getSubtitleTrackCount.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiGetSubtitleTrackCountResponse
 */
video_player_linuxLinuxVideoPlayerApiGetSubtitleTrackCountResponse* video_player_linux_linux_video_player_api_get_subtitle_track_count_response_new(int64_t return_value);

/**
 * video_player_linux_linux_video_player_api_get_subtitle_track_count_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.getSubtitleTrackCount.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiGetSubtitleTrackCountResponse
 */
video_player_linuxLinuxVideoPlayerApiGetSubtitleTrackCountResponse* video_player_linux_linux_video_player_api_get_subtitle_track_count_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetSubtitleTrackResponse, video_player_linux_linux_video_player_api_set_subtitle_track_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_SUBTITLE_TRACK_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_subtitle_track_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setSubtitleTrack.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetSubtitleTrackResponse
 */
video_player_linuxLinuxVideoPlayerApiSetSubtitleTrackResponse* video_player_linux_linux_video_player_api_set_subtitle_track_response_new();

/**
 * video_player_linux_linux_video_player_api_set_subtitle_track_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setSubtitleTrack.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetSubtitleTrackResponse
 */
video_player_linuxLinuxVideoPlayerApiSetSubtitleTrackResponse* video_player_linux_linux_video_player_api_set_subtitle_track_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetSubtitleUriResponse, video_player_linux_linux_video_player_api_set_subtitle_uri_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_SUBTITLE_URI_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_subtitle_uri_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setSubtitleUri.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetSubtitleUriResponse
 */
video_player_linuxLinuxVideoPlayerApiSetSubtitleUriResponse* video_player_linux_linux_video_player_api_set_subtitle_uri_response_new();

/**
 * video_player_linux_linux_video_player_api_set_subtitle_uri_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setSubtitleUri.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetSubtitleUriResponse
 */
video_player_linuxLinuxVideoPlayerApiSetSubtitleUriResponse* video_player_linux_linux_video_player_api_set_subtitle_uri_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetSubtitleFontResponse, video_player_linux_linux_video_player_api_set_subtitle_font_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_SUBTITLE_FONT_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_subtitle_font_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setSubtitleFont.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetSubtitleFontResponse
 */
video_player_linuxLinuxVideoPlayerApiSetSubtitleFontResponse* video_player_linux_linux_video_player_api_set_subtitle_font_response_new();

/**
 * video_player_linux_linux_video_player_api_set_subtitle_font_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setSubtitleFont.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetSubtitleFontResponse
 */
video_player_linuxLinuxVideoPlayerApiSetSubtitleFontResponse* video_player_linux_linux_video_player_api_set_subtitle_font_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetChannelMixPresetResponse, video_player_linux_linux_video_player_api_set_channel_mix_preset_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_CHANNEL_MIX_PRESET_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_channel_mix_preset_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setChannelMixPreset.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetChannelMixPresetResponse
 */
video_player_linuxLinuxVideoPlayerApiSetChannelMixPresetResponse* video_player_linux_linux_video_player_api_set_channel_mix_preset_response_new();

/**
 * video_player_linux_linux_video_player_api_set_channel_mix_preset_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setChannelMixPreset.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetChannelMixPresetResponse
 */
video_player_linuxLinuxVideoPlayerApiSetChannelMixPresetResponse* video_player_linux_linux_video_player_api_set_channel_mix_preset_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetEqualizerResponse, video_player_linux_linux_video_player_api_set_equalizer_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_EQUALIZER_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_equalizer_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setEqualizer.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetEqualizerResponse
 */
video_player_linuxLinuxVideoPlayerApiSetEqualizerResponse* video_player_linux_linux_video_player_api_set_equalizer_response_new();

/**
 * video_player_linux_linux_video_player_api_set_equalizer_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setEqualizer.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetEqualizerResponse
 */
video_player_linuxLinuxVideoPlayerApiSetEqualizerResponse* video_player_linux_linux_video_player_api_set_equalizer_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetVideoBalanceResponse, video_player_linux_linux_video_player_api_set_video_balance_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_VIDEO_BALANCE_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_video_balance_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setVideoBalance.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetVideoBalanceResponse
 */
video_player_linuxLinuxVideoPlayerApiSetVideoBalanceResponse* video_player_linux_linux_video_player_api_set_video_balance_response_new();

/**
 * video_player_linux_linux_video_player_api_set_video_balance_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setVideoBalance.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetVideoBalanceResponse
 */
video_player_linuxLinuxVideoPlayerApiSetVideoBalanceResponse* video_player_linux_linux_video_player_api_set_video_balance_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetAudioPassthroughResponse, video_player_linux_linux_video_player_api_set_audio_passthrough_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_AUDIO_PASSTHROUGH_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_audio_passthrough_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setAudioPassthrough.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetAudioPassthroughResponse
 */
video_player_linuxLinuxVideoPlayerApiSetAudioPassthroughResponse* video_player_linux_linux_video_player_api_set_audio_passthrough_response_new();

/**
 * video_player_linux_linux_video_player_api_set_audio_passthrough_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setAudioPassthrough.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetAudioPassthroughResponse
 */
video_player_linuxLinuxVideoPlayerApiSetAudioPassthroughResponse* video_player_linux_linux_video_player_api_set_audio_passthrough_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(video_player_linuxLinuxVideoPlayerApiSetChannelMixMatrixResponse, video_player_linux_linux_video_player_api_set_channel_mix_matrix_response, VIDEO_PLAYER_LINUX, LINUX_VIDEO_PLAYER_API_SET_CHANNEL_MIX_MATRIX_RESPONSE, GObject)

/**
 * video_player_linux_linux_video_player_api_set_channel_mix_matrix_response_new:
 *
 * Creates a new response to LinuxVideoPlayerApi.setChannelMixMatrix.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetChannelMixMatrixResponse
 */
video_player_linuxLinuxVideoPlayerApiSetChannelMixMatrixResponse* video_player_linux_linux_video_player_api_set_channel_mix_matrix_response_new();

/**
 * video_player_linux_linux_video_player_api_set_channel_mix_matrix_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to LinuxVideoPlayerApi.setChannelMixMatrix.
 *
 * Returns: a new #video_player_linuxLinuxVideoPlayerApiSetChannelMixMatrixResponse
 */
video_player_linuxLinuxVideoPlayerApiSetChannelMixMatrixResponse* video_player_linux_linux_video_player_api_set_channel_mix_matrix_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * video_player_linuxLinuxVideoPlayerApiVTable:
 *
 * Table of functions exposed by LinuxVideoPlayerApi to be implemented by the API provider.
 */
typedef struct {
  video_player_linuxLinuxVideoPlayerApiInitializeResponse* (*initialize)(gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiCreateResponse* (*create)(const gchar* asset, const gchar* uri, FlValue* http_headers, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiDisposeResponse* (*dispose)(int64_t texture_id, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetLoopingResponse* (*set_looping)(int64_t texture_id, gboolean is_looping, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetVolumeResponse* (*set_volume)(int64_t texture_id, double volume, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetPlaybackSpeedResponse* (*set_playback_speed)(int64_t texture_id, double speed, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiPlayResponse* (*play)(int64_t texture_id, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiGetPositionResponse* (*get_position)(int64_t texture_id, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSeekToResponse* (*seek_to)(int64_t texture_id, int64_t position, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiPauseResponse* (*pause)(int64_t texture_id, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiGetAudioTrackCountResponse* (*get_audio_track_count)(int64_t texture_id, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetAudioTrackResponse* (*set_audio_track)(int64_t texture_id, int64_t track_index, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetOutputChannelsResponse* (*set_output_channels)(int64_t texture_id, int64_t channels, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetMuteResponse* (*set_mute)(int64_t texture_id, gboolean mute, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiIsAudioOnlyResponse* (*is_audio_only)(int64_t texture_id, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetScaleMethodResponse* (*set_scale_method)(int64_t texture_id, int64_t method, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetAVOffsetResponse* (*set_a_v_offset)(int64_t texture_id, int64_t offset_ms, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetSubtitlesEnabledResponse* (*set_subtitles_enabled)(int64_t texture_id, gboolean enabled, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiGetSubtitleTrackCountResponse* (*get_subtitle_track_count)(int64_t texture_id, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetSubtitleTrackResponse* (*set_subtitle_track)(int64_t texture_id, int64_t track_index, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetSubtitleUriResponse* (*set_subtitle_uri)(int64_t texture_id, const gchar* uri, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetSubtitleFontResponse* (*set_subtitle_font)(int64_t texture_id, const gchar* font_desc, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetChannelMixPresetResponse* (*set_channel_mix_preset)(int64_t texture_id, const gchar* preset, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetEqualizerResponse* (*set_equalizer)(int64_t texture_id, FlValue* bands, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetVideoBalanceResponse* (*set_video_balance)(int64_t texture_id, double brightness, double contrast, double saturation, double hue, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetAudioPassthroughResponse* (*set_audio_passthrough)(int64_t texture_id, gboolean enabled, gpointer user_data);
  video_player_linuxLinuxVideoPlayerApiSetChannelMixMatrixResponse* (*set_channel_mix_matrix)(int64_t texture_id, int64_t in_channels, int64_t out_channels, FlValue* matrix, gpointer user_data);
} video_player_linuxLinuxVideoPlayerApiVTable;

/**
 * video_player_linux_linux_video_player_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the LinuxVideoPlayerApi API.
 */
void video_player_linux_linux_video_player_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const video_player_linuxLinuxVideoPlayerApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * video_player_linux_linux_video_player_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the LinuxVideoPlayerApi API.
 */
void video_player_linux_linux_video_player_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
