name: "CI (Reusable)"

on:
  workflow_call:
    inputs:
      package-path:
        description: "Path to the package to check"
        required: true
        default: "packages/filament_scene"

jobs:
  check-package:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: "${{ inputs.package-path }}"
      flutter_version: 3.32.0
      runs_on: ubuntu-latest
      setup: flutter doctor --verbose
      concurrency: 4
  check-example:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package_example.yml@v1
    with:
      working_directory: "${{ inputs.package-path }}/example"
      flutter_version: 3.32.0
      runs_on: ubuntu-latest
      setup: flutter doctor --verbose
      concurrency: 4