name: "filament_scene"

on:
  pull_request:
    paths:
      # in packages/filament_scene
      - "packages/filament_scene/pubspec.yaml"
      - "packages/filament_scene/analysis_options.yaml"
      - "packages/filament_scene/pubspec.lock"
      - "packages/filament_scene/lib/**"
      - "packages/filament_scene/test/**"
      - "packages/filament_scene/linux_cpp/**"
      - "packages/filament_scene/pigeons/**"
      # in packages/filament_scene/example
      - "packages/filament_scene/example/pubspec.yaml"
      - "packages/filament_scene/example/lib/**"
      - "packages/filament_scene/example/test/**"
      - "packages/filament_scene/example/assets/**"
      # workflow definition itself
      - ".github/workflows/filament_scene.yaml"
      - ".github/workflows/ci.yaml"
  push:
    branches:
      - main
    paths:
      # in packages/filament_scene
      - "packages/filament_scene/pubspec.yaml"
      - "packages/filament_scene/analysis_options.yaml"
      - "packages/filament_scene/pubspec.lock"
      - "packages/filament_scene/lib/**"
      - "packages/filament_scene/test/**"
      - "packages/filament_scene/linux_cpp/**"
      - "packages/filament_scene/pigeons/**"
      # in packages/filament_scene/example
      - "packages/filament_scene/example/pubspec.yaml"
      - "packages/filament_scene/example/lib/**"
      - "packages/filament_scene/example/test/**"
      - "packages/filament_scene/example/assets/**"
      # workflow definition itself
      - ".github/workflows/filament_scene.yaml"
      - ".github/workflows/ci.yaml"

jobs:
  run_checks:
    uses: .github/workflows/ci.yaml@v1
    with:
      package-path: "packages/filament_scene"