name: spell-check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/spell-check.yaml"
      - ".github/cspell.json"
      - "**/*.md|"
      - "!brick/**/*.md|"
      - ".*/**/*.md"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/spell-check.yaml"
      - ".github/cspell.json"
      - "**/*.md|"
      - "!brick/**/*.md|"
      - ".*/**/*.md"

jobs:
  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
        !brick/**/*.md
        .*/**/*.md
      modified_files_only: false
