name: "video_player"

on:
  pull_request:
    paths:
      # in packages/video_player/video_player_linux
      - "packages/video_player/video_player_linux/pubspec.yaml"
      - "packages/video_player/video_player_linux/analysis_options.yaml"
      - "packages/video_player/video_player_linux/pubspec.lock"
      - "packages/video_player/video_player_linux/lib/**"
      - "packages/video_player/video_player_linux/test/**"
      - "packages/video_player/video_player_linux/linux_cpp/**"
      - "packages/video_player/video_player_linux/pigeons/**"
      # in packages/video_player/video_player_linux/example
      - "packages/video_player/video_player_linux/example/pubspec.yaml"
      - "packages/video_player/video_player_linux/example/lib/**"
      - "packages/video_player/video_player_linux/example/test/**"
      - "packages/video_player/video_player_linux/example/assets/**"
      # workflow definition itself
      - ".github/workflows/video_player.yaml"
      - ".github/workflows/ci.yaml"
  push:
    branches:
      - main
    paths:
      # in packages/video_player/video_player_linux
      - "packages/video_player/video_player_linux/pubspec.yaml"
      - "packages/video_player/video_player_linux/analysis_options.yaml"
      - "packages/video_player/video_player_linux/pubspec.lock"
      - "packages/video_player/video_player_linux/lib/**"
      - "packages/video_player/video_player_linux/test/**"
      - "packages/video_player/video_player_linux/linux_cpp/**"
      - "packages/video_player/video_player_linux/pigeons/**"
      # in packages/video_player/video_player_linux/example
      - "packages/video_player/video_player_linux/example/pubspec.yaml"
      - "packages/video_player/video_player_linux/example/lib/**"
      - "packages/video_player/video_player_linux/example/test/**"
      - "packages/video_player/video_player_linux/example/assets/**"
      # workflow definition itself
      - ".github/workflows/video_player.yaml"
      - ".github/workflows/ci.yaml"

jobs:
  run_checks:
    uses: .github/workflows/ci.yaml@v1
    with:
      package-path: "packages/video_player/video_player_linux"