name: "webview"

on:
  pull_request:
    paths:
      # in packages/webview/webview_flutter_linux
      - "packages/webview/webview_flutter_linux/pubspec.yaml"
      - "packages/webview/webview_flutter_linux/analysis_options.yaml"
      - "packages/webview/webview_flutter_linux/pubspec.lock"
      - "packages/webview/webview_flutter_linux/lib/**"
      - "packages/webview/webview_flutter_linux/test/**"
      - "packages/webview/webview_flutter_linux/linux_cpp/**"
      - "packages/webview/webview_flutter_linux/pigeons/**"
      # in packages/webview/webview_flutter_linux/example
      - "packages/webview/webview_flutter_linux/example/pubspec.yaml"
      - "packages/webview/webview_flutter_linux/example/lib/**"
      - "packages/webview/webview_flutter_linux/example/test/**"
      - "packages/webview/webview_flutter_linux/example/assets/**"
      # workflow definition itself
      - ".github/workflows/webview.yaml"
      - ".github/workflows/ci.yaml"
  push:
    branches:
      - main
    paths:
      # in packages/webview/webview_flutter_linux
      - "packages/webview/webview_flutter_linux/pubspec.yaml"
      - "packages/webview/webview_flutter_linux/analysis_options.yaml"
      - "packages/webview/webview_flutter_linux/pubspec.lock"
      - "packages/webview/webview_flutter_linux/lib/**"
      - "packages/webview/webview_flutter_linux/test/**"
      - "packages/webview/webview_flutter_linux/linux_cpp/**"
      - "packages/webview/webview_flutter_linux/pigeons/**"
      # in packages/webview/webview_flutter_linux/example
      - "packages/webview/webview_flutter_linux/example/pubspec.yaml"
      - "packages/webview/webview_flutter_linux/example/lib/**"
      - "packages/webview/webview_flutter_linux/example/test/**"
      - "packages/webview/webview_flutter_linux/example/assets/**"
      # workflow definition itself
      - ".github/workflows/webview.yaml"
      - ".github/workflows/ci.yaml"

jobs:
  run_checks:
    uses: ./.github/workflows/ci.yaml
    with:
      package-path: "packages/webview/webview_flutter_linux"